### PR TITLE
Enable thinning

### PR DESCRIPTION
**Pull request by hellemo**
Thinning was hard coded to 1, this enables the thinning parameter set in model to be used by JAGS. 

Sorry about all the whitespace changes, may be an editor issue (I'm using Atom), not quite sure what is the best way to fix that.

### CODE REVIEW

**Comment by goedman** [comment]
HI @hellemo ,

Thanks for helping out!

Need to think about this. It's been a long time since I dove into this issue of thinning by Jags vs. later on by Mamba. I think the issue is that when choosing thinning by Jags e.g. the line1 example with deviance=true will fail.

On your system, does Pkg.test("Jags") complete?

Regards,
Rob

**Comment by goedman** [comment]
@hellemo , I'm also a bit confused by the state of the repository right now. I merged your PR, then noticed the line1 problem, reverted the PR, but the problem remains. Going back to the latest tagged version (v"1.0.2") works, but Pkg.checkout("Jags") still fails. Weird.

**Comment by hellemo** [comment]
The thing is that I need thinning in Jags because it is very slow and memory intensive with no thinning, giving problems when reading and processing the txt files. With the larger instances Julia actually crashes  (32-bit) due to memory issues.

It's quite possible that it needs some more work, though, but this was sufficient to make my models run smoothly. Unfortunately, I can't get the tests running on my system at all for some reason.

I'm new to Git, so I can't help with that. (I tried to rebase/squash, but ended up with 4 commits instead of 2)

**Comment by goedman** [comment]
You are ok for now using your version? I'm traveling next week, so not sure how much time I will be able to spend on this. One interim solution I can think of is that we create a separate branch.

Which platform are you on? Maybe it was in fact the rebase/sqaush that caused the Git problem, but we'll fix that before tagging a next version.

**Comment by goedman** [comment]
Maybe a reasonable solution is to introduce a field in the jagsmodel called "jagsthin" and then adjust the Mamba thin later on. I'll play around with this approach a bit more.

**Comment by hellemo** [comment]
I got the tests working on a different computer, trying out a proposed fix now.

**Comment by goedman** [comment]
Great, let me know how it goes. About to take off, so will have a look tomorrow.

**Comment by hellemo** [comment]
Latest commit passes all tests on my system. Have a look when you find the time.

**Comment by hellemo** [comment]
On second thought, the extra zeros might give incorrect results. My first idea was to "pad" with NAs, would it be possible to send a nullable array to Mamba?

**Comment by goedman** [comment]
Don't think so, Mamba chains are not nullable fields as far as I know. But if we know jagsthin and (mamba) thin (as fields in a Jagsmodel we can adjust the size of a3d and generate correct Mamba chains. I guess in most cases one would either do thinning in Jags or in Mamba but I would prefer to be able to deal with even mixed thinning. One issue is if the number of samples is not a multiple of the Jags thinning factor. Maybe we just loose some samples in that case.

**Comment by hellemo** [comment]
I had another go this morning. I manually thin only chains that do not have the expected size, (deviance in the test). Not sure if it is safe to assume the final chain has correct length, though (We already know we cannot trust the first).

**Comment by goedman** [comment]
I have just merged an update to master which accepts a jagsthin argument to Jagsmodel. See if that works for you. Added examples Line3 and Line4 and corresponding test runs in runtests.jl.

**Comment by hellemo** [comment]
Great! That works for me (and tests, too). Thanks a lot for following up so swiftly! (Any chance of  tagging a new version, too?)

What is the use case for thinning after reading the full chains? Seems very inefficient, especially considering how slow and memory intensive readdlm is.

**Comment by goedman** [comment]
Nice. I'll spend some time on checking how far away Stan.jl and Jags.jl are from Julia v0.6. If that might take quite a while, I'll tag an interim version. But for now the master should always work.

I need to check the mamba diagnostics to answer your use case question and you might be very well correct that there is no use case, but I would like to check that. Also, if that is the case jagsthin should be thin and the current thin renamed to mambathin.

Also would like to have a closer at the special treatment of deviance in Jags.

Rob

**Comment by goedman** [comment]
Figured out the deviance issue. Turns out Jags does not store adaptations samples when (jags)thin != 1. Furthermore, deviance also accepts a thin(...) keyword, I added that in the generated bugs file. This makes the corrections I applied in jags() simpler. In latest master.

**Comment by hellemo** [comment]
Did you push the last set of changes?

**Comment by goedman** [comment]
I did just now. Sorry about that.

**Comment by hellemo** [comment]
Looks good to me.

Makes the case for reading full chains only to discard most of the data immediately before creating the Mamba Chains even weaker, though, doesn't it?

**Comment by goedman** [comment]
Yip, I agree.

**Pull request merged**
